-- =============================================================================
-- CareShift — PostgreSQL schema (mirrors EF Core migrations exactly)
-- Run this on a fresh database before seed.sql.
-- Column names and types match what the .NET application expects.
-- =============================================================================

-- Drop in reverse dependency order (safe to re-run on a fresh DB)
DROP TABLE IF EXISTS "SwapAuditEntries"     CASCADE;
DROP TABLE IF EXISTS "ShiftSwapRequests"    CASCADE;
DROP TABLE IF EXISTS "LeaveAuditEntries"    CASCADE;
DROP TABLE IF EXISTS "LeaveRequests"        CASCADE;
DROP TABLE IF EXISTS "RefreshTokens"        CASCADE;
DROP TABLE IF EXISTS "Shifts"               CASCADE;
DROP TABLE IF EXISTS "Staff"                CASCADE;
DROP TABLE IF EXISTS "Departments"          CASCADE;

-- =============================================================================
-- DEPARTMENTS
-- =============================================================================
CREATE TABLE "Departments" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"        character varying(100) NOT NULL,
    "Description" character varying(500),
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Departments_Name" ON "Departments" ("Name");

-- =============================================================================
-- STAFF
-- Enum values stored as text: Admin | DepartmentLead | ChargeNurse | Doctor | Nurse | Receptionist
-- EmploymentType:             FullTime | PartTime | Contract
-- =============================================================================
CREATE TABLE "Staff" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName"       character varying(100) NOT NULL,
    "Email"          character varying(200) NOT NULL,
    "PasswordHash"   text                   NOT NULL,
    "Role"           text                   NOT NULL,
    "DepartmentId"   integer                NOT NULL,
    "IsActive"       boolean                NOT NULL DEFAULT TRUE,
    "Phone"          character varying(30),
    "Initials"       character varying(5)   NOT NULL,
    "EmploymentType" text                   NOT NULL DEFAULT 'FullTime',
    "CreatedAt"      timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Staff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Staff_Departments_DepartmentId"
        FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Staff_Email"        ON "Staff" ("Email");
CREATE INDEX        "IX_Staff_DepartmentId" ON "Staff" ("DepartmentId");

-- =============================================================================
-- REFRESH TOKENS
-- =============================================================================
CREATE TABLE "RefreshTokens" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Token"     character varying(256)   NOT NULL,
    "StaffId"   integer                  NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean                  NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Staff_StaffId"
        FOREIGN KEY ("StaffId") REFERENCES "Staff" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_RefreshTokens_Token"     ON "RefreshTokens" ("Token");
CREATE INDEX        "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");

-- =============================================================================
-- SHIFTS
-- ShiftType stored as text: Morning | Afternoon | Night
-- StartTime/EndTime in UTC: Morning 07-15, Afternoon 15-23, Night 23-07(+1d)
-- =============================================================================
CREATE TABLE "Shifts" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
    "StaffId"      integer                  NOT NULL,
    "DepartmentId" integer                  NOT NULL,
    "StartTime"    timestamp with time zone NOT NULL,
    "EndTime"      timestamp with time zone NOT NULL,
    "ShiftType"    text                     NOT NULL,
    "Notes"        character varying(500),
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shifts_Staff_StaffId"
        FOREIGN KEY ("StaffId")      REFERENCES "Staff"       ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Shifts_Departments_DepartmentId"
        FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Shifts_StaffId"      ON "Shifts" ("StaffId");
CREATE INDEX "IX_Shifts_DepartmentId" ON "Shifts" ("DepartmentId");

-- =============================================================================
-- LEAVE REQUESTS
-- LeaveType:   Annual | Sick | Training | Personal
-- Status:      Pending | Approved | Rejected
-- =============================================================================
CREATE TABLE "LeaveRequests" (
    "Id"            integer                  GENERATED BY DEFAULT AS IDENTITY,
    "StaffId"       integer                  NOT NULL,
    "LeaveType"     text                     NOT NULL,
    "StartDate"     date                     NOT NULL,
    "EndDate"       date                     NOT NULL,
    "Reason"        character varying(500)   NOT NULL,
    "Status"        text                     NOT NULL DEFAULT 'Pending',
    "ReviewedById"  integer,
    "ReviewedAt"    timestamp with time zone,
    "ReviewNote"    character varying(500),
    "SubmittedAt"   timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_Staff_StaffId"
        FOREIGN KEY ("StaffId")      REFERENCES "Staff" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveRequests_Staff_ReviewedById"
        FOREIGN KEY ("ReviewedById") REFERENCES "Staff" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_LeaveRequests_StaffId"      ON "LeaveRequests" ("StaffId");
CREATE INDEX "IX_LeaveRequests_ReviewedById" ON "LeaveRequests" ("ReviewedById");

-- =============================================================================
-- LEAVE AUDIT ENTRIES  (immutable per-request event trail)
-- =============================================================================
CREATE TABLE "LeaveAuditEntries" (
    "Id"             integer                  GENERATED BY DEFAULT AS IDENTITY,
    "LeaveRequestId" integer                  NOT NULL,
    "At"             timestamp with time zone NOT NULL DEFAULT NOW(),
    "By"             text                     NOT NULL,
    "Action"         text                     NOT NULL,  -- submitted | approved | rejected
    "Note"           text,
    CONSTRAINT "PK_LeaveAuditEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveAuditEntries_LeaveRequests_LeaveRequestId"
        FOREIGN KEY ("LeaveRequestId") REFERENCES "LeaveRequests" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_LeaveAuditEntries_LeaveRequestId" ON "LeaveAuditEntries" ("LeaveRequestId");

-- =============================================================================
-- SHIFT SWAP REQUESTS
-- Status: PendingRequestee | PendingAdmin | Approved | Rejected | Cancelled
-- =============================================================================
CREATE TABLE "ShiftSwapRequests" (
    "Id"                integer                  GENERATED BY DEFAULT AS IDENTITY,
    "RequesterId"       integer                  NOT NULL,
    "RequesteeId"       integer                  NOT NULL,
    "RequesterShiftId"  integer                  NOT NULL,
    "RequesteeShiftId"  integer                  NOT NULL,
    "Reason"            character varying(500)   NOT NULL,
    "Status"            text                     NOT NULL DEFAULT 'PendingRequestee',
    "SubmittedAt"       timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShiftSwapRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShiftSwapRequests_Staff_RequesterId"
        FOREIGN KEY ("RequesterId")      REFERENCES "Staff"  ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShiftSwapRequests_Staff_RequesteeId"
        FOREIGN KEY ("RequesteeId")      REFERENCES "Staff"  ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShiftSwapRequests_Shifts_RequesterShiftId"
        FOREIGN KEY ("RequesterShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShiftSwapRequests_Shifts_RequesteeShiftId"
        FOREIGN KEY ("RequesteeShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_ShiftSwapRequests_RequesterId"      ON "ShiftSwapRequests" ("RequesterId");
CREATE INDEX "IX_ShiftSwapRequests_RequesteeId"      ON "ShiftSwapRequests" ("RequesteeId");
CREATE INDEX "IX_ShiftSwapRequests_RequesterShiftId" ON "ShiftSwapRequests" ("RequesterShiftId");
CREATE INDEX "IX_ShiftSwapRequests_RequesteeShiftId" ON "ShiftSwapRequests" ("RequesteeShiftId");

-- =============================================================================
-- SWAP AUDIT ENTRIES
-- =============================================================================
CREATE TABLE "SwapAuditEntries" (
    "Id"                   integer                  GENERATED BY DEFAULT AS IDENTITY,
    "ShiftSwapRequestId"   integer                  NOT NULL,
    "At"                   timestamp with time zone NOT NULL DEFAULT NOW(),
    "By"                   text                     NOT NULL,
    "Action"               text                     NOT NULL,  -- submitted | accepted | declined | approved | rejected
    "Note"                 text,
    CONSTRAINT "PK_SwapAuditEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SwapAuditEntries_ShiftSwapRequests_ShiftSwapRequestId"
        FOREIGN KEY ("ShiftSwapRequestId") REFERENCES "ShiftSwapRequests" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SwapAuditEntries_ShiftSwapRequestId" ON "SwapAuditEntries" ("ShiftSwapRequestId");

-- =============================================================================
-- EF Core migrations history table (prevents the app from re-running migrations)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20260421060458_InitialCreate',   '10.0.6'),
    ('20260515152546_RemoveAuditLog',  '10.0.6'),
    ('20260516133720_AddRefreshToken', '10.0.6')
ON CONFLICT DO NOTHING;
